# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: tomo_left_arm
  joint_model_group_pose: left_arm_home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_1_head
    - joint_2_head
    - joint_1_left
    - joint_2_left
    - joint_3_left
    - joint_4_left
    - joint_5_left
    - joint_6_left
    - joint_1_right
    - joint_2_right
    - joint_3_right
    - joint_4_right
    - joint_5_right
    - hand_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
tomo_left_arm_controller:
  type: position_controllers/JointPositionController
  joints:
    - joint_1_left
    - joint_2_left
    - joint_3_left
    - joint_4_left
    - joint_5_left
    - joint_6_left
  gains:
    joint_1_left:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_2_left:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_3_left:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_4_left:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_5_left:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_6_left:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
left_hand_controller:
  type: position_controllers/JointPositionController
  joints:
    joint_6_left
  gains:
    joint_6_left:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
tomo_right_arm_controller:
  type: position_controllers/JointPositionController
  joints:
    - joint_1_right
    - joint_2_right
    - joint_3_right
    - joint_4_right
    - joint_5_right
    - hand_joint
  gains:
    joint_1_right:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_2_right:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_3_right:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_4_right:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_5_right:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    hand_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
right_hand_controller:
  type: position_controllers/JointPositionController
  joints:
    hand_joint
  gains:
    hand_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1